# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         cpan2rpm
version:      2.020
version_from: cpan2rpm
installdirs:  site
requires:
    ExtUtils::MakeMaker:           5.4302
    HTTP::Request:                 0
    LWP::UserAgent:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
